// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

#nullable disable

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20230126220616_AddDislikeField")]
    partial class AddDislikeField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 11,
                            Body = "Quidem placeat voluptas eum tenetur inventore.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4427),
                            PostId = 12,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4475)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 14,
                            Body = "Quo suscipit necessitatibus perspiciatis natus iure sed ex quaerat.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4577),
                            PostId = 4,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4582)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 15,
                            Body = "Ut suscipit neque rerum voluptatem.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4618),
                            PostId = 13,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4621)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            Body = "Officia est et assumenda sunt excepturi.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4657),
                            PostId = 18,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4660)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 17,
                            Body = "Magnam recusandae laborum cum.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4692),
                            PostId = 13,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4695)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            Body = "Nulla explicabo aperiam asperiores corrupti quis fugiat ut vel eum.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4742),
                            PostId = 7,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4745)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 21,
                            Body = "Est nam quo.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4777),
                            PostId = 8,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4779)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            Body = "Voluptatibus omnis id et sequi.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4808),
                            PostId = 14,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4811)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 9,
                            Body = "Nesciunt et eligendi fugiat molestias asperiores quod nihil sed.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4855),
                            PostId = 15,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4857)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            Body = "Non dolorum vero voluptas sit.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4894),
                            PostId = 16,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4897)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 13,
                            Body = "Tempora enim distinctio qui illum et aut accusantium et.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4944),
                            PostId = 16,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4947)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 3,
                            Body = "Atque consequuntur fuga sit atque laborum temporibus nisi.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4986),
                            PostId = 17,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(4989)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 15,
                            Body = "Sapiente optio temporibus.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5014),
                            PostId = 5,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5016)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 3,
                            Body = "Itaque reprehenderit aut et.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5046),
                            PostId = 4,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5049)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 15,
                            Body = "Quibusdam nisi voluptates et in aliquid delectus.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5083),
                            PostId = 2,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5086)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 4,
                            Body = "Dolor molestiae et cum.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5113),
                            PostId = 18,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5115)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 9,
                            Body = "Quis consequuntur incidunt veritatis expedita assumenda eveniet autem culpa.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5156),
                            PostId = 2,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5159)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 16,
                            Body = "Quis quidem est et magnam exercitationem voluptas enim.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5194),
                            PostId = 6,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5198)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 7,
                            Body = "Cum aperiam corrupti debitis sequi quia veniam.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5232),
                            PostId = 10,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5235)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 1,
                            Body = "Nulla ullam qui doloribus accusamus rem.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5267),
                            PostId = 7,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 849, DateTimeKind.Local).AddTicks(5270)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDislike")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 17,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(6859),
                            IsDislike = true,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(6904),
                            UserId = 16
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 15,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(6955),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(6958),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 8,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(6976),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(6979),
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 5,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(6995),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(6998),
                            UserId = 21
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 19,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7019),
                            IsDislike = true,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7022),
                            UserId = 20
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 7,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7037),
                            IsDislike = true,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7039),
                            UserId = 5
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 8,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7052),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7055),
                            UserId = 10
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 10,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7073),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7076),
                            UserId = 15
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 2,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7089),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7091),
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 16,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7104),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7106),
                            UserId = 5
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 14,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7121),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7123),
                            UserId = 15
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 12,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7137),
                            IsDislike = true,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7140),
                            UserId = 9
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 12,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7153),
                            IsDislike = true,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7156),
                            UserId = 12
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 6,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7169),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7171),
                            UserId = 18
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 16,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7185),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7187),
                            UserId = 17
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 16,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7200),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7202),
                            UserId = 11
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 7,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7216),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7218),
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 10,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7230),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7232),
                            UserId = 9
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 6,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7244),
                            IsDislike = true,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7246),
                            UserId = 17
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 10,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7258),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 852, DateTimeKind.Local).AddTicks(7261),
                            UserId = 14
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9699),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/807.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9750)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9806),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/25.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9810)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9820),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/677.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9823)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9832),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/927.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9834)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9843),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/448.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9846)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9854),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1043.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9857)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9864),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/52.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9866)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9875),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/884.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9877)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9885),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/956.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9887)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9894),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/355.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9896)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9903),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/307.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9905)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9913),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/156.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9915)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9923),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/763.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 797, DateTimeKind.Local).AddTicks(9925)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 798, DateTimeKind.Local).AddTicks(15),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/383.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 798, DateTimeKind.Local).AddTicks(17)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 798, DateTimeKind.Local).AddTicks(26),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/243.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 798, DateTimeKind.Local).AddTicks(28)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 798, DateTimeKind.Local).AddTicks(36),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/847.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 798, DateTimeKind.Local).AddTicks(38)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 798, DateTimeKind.Local).AddTicks(46),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/611.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 798, DateTimeKind.Local).AddTicks(48)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 798, DateTimeKind.Local).AddTicks(56),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1198.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 798, DateTimeKind.Local).AddTicks(58)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 798, DateTimeKind.Local).AddTicks(66),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/713.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 798, DateTimeKind.Local).AddTicks(69)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 798, DateTimeKind.Local).AddTicks(76),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/929.jpg",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 798, DateTimeKind.Local).AddTicks(78)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4657),
                            URL = "https://picsum.photos/640/480/?image=822",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4715)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4772),
                            URL = "https://picsum.photos/640/480/?image=850",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4775)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4787),
                            URL = "https://picsum.photos/640/480/?image=219",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4789)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4800),
                            URL = "https://picsum.photos/640/480/?image=334",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4803)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4812),
                            URL = "https://picsum.photos/640/480/?image=211",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4815)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4824),
                            URL = "https://picsum.photos/640/480/?image=708",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4827)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4835),
                            URL = "https://picsum.photos/640/480/?image=213",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4838)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4847),
                            URL = "https://picsum.photos/640/480/?image=40",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4849)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4858),
                            URL = "https://picsum.photos/640/480/?image=181",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4860)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4869),
                            URL = "https://picsum.photos/640/480/?image=261",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4871)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4880),
                            URL = "https://picsum.photos/640/480/?image=886",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4882)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4891),
                            URL = "https://picsum.photos/640/480/?image=652",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4893)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4902),
                            URL = "https://picsum.photos/640/480/?image=707",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4904)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4913),
                            URL = "https://picsum.photos/640/480/?image=944",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4915)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4930),
                            URL = "https://picsum.photos/640/480/?image=510",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4932)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4941),
                            URL = "https://picsum.photos/640/480/?image=280",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4943)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4953),
                            URL = "https://picsum.photos/640/480/?image=740",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4955)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4964),
                            URL = "https://picsum.photos/640/480/?image=78",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4966)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4975),
                            URL = "https://picsum.photos/640/480/?image=842",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4978)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4986),
                            URL = "https://picsum.photos/640/480/?image=430",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 800, DateTimeKind.Local).AddTicks(4988)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PreviewId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 15,
                            Body = "Reprehenderit officia aliquid ex culpa laborum.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(6563),
                            PreviewId = 37,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(6628)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 10,
                            Body = "Ex qui illo.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(6761),
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(6766)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 14,
                            Body = "Et ratione dignissimos sint sit quas in quis.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(6866),
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(6870)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 20,
                            Body = "Et delectus nihil temporibus magnam adipisci id aut adipisci. Possimus officiis et at. Eos harum reprehenderit asperiores sed explicabo expedita. Ut sint tempore similique. Similique quasi quia natus et blanditiis. Occaecati expedita quod mollitia assumenda modi dicta veritatis reiciendis corporis.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7278),
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7285)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 4,
                            Body = "Quisquam mollitia sint et temporibus qui consequatur.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7348),
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7353)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 21,
                            Body = "nostrum",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7376),
                            PreviewId = 30,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7380)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 12,
                            Body = "Est inventore facilis sed placeat qui quibusdam. Nostrum et in ratione. Fugit enim non asperiores similique perferendis mollitia quis qui nobis.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7510),
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7516)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            Body = "facere",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7552),
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7557)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 13,
                            Body = "Odio rem soluta.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7610),
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7614)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            Body = "Rerum dolores veritatis fuga excepturi voluptatem quisquam. Rerum odit enim. Est rem consequatur ut quis modi omnis veritatis numquam libero. Dolor voluptas enim et.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7799),
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7805)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 14,
                            Body = "Reprehenderit nostrum fuga hic eos aspernatur.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7871),
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7877)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 6,
                            Body = "est",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7918),
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(7921)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 10,
                            Body = "Dicta et veritatis deleniti cupiditate.\nDoloribus velit alias mollitia sed voluptatibus.\nQui esse dicta sequi earum facere.\nQuisquam architecto enim magni tempore aliquid.\nAlias illum qui autem.\nVoluptatem similique velit et quos voluptatem amet dolore libero.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8067),
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8072)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 6,
                            Body = "Porro officiis aut quia est ex incidunt aut. Odit dolores officiis id sed consequuntur ut veritatis sint accusantium. Animi soluta commodi earum exercitationem asperiores dolorem reiciendis. Ea maxime et qui quibusdam non harum quibusdam.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8244),
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8248)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 3,
                            Body = "Officia ut odio voluptate ea porro veniam sed tenetur.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8405),
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8409)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 6,
                            Body = "Atque possimus voluptatem porro.\nMaxime reiciendis quia ex vero laboriosam aliquam perspiciatis.\nRepellendus dolor cupiditate consequatur accusamus molestiae sed magnam repellat.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8492),
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8495)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 3,
                            Body = "Qui illum enim autem doloremque quod est error cum sequi.\nEt voluptas occaecati.\nVoluptatem deleniti consequatur est sed iusto quam et.\nLaborum voluptatum consequuntur recusandae odio et.\nArchitecto voluptatem fugit et dolorem.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8688),
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8691)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 17,
                            Body = "Quas et ipsa omnis cum aut vel.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8738),
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8741)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 18,
                            Body = "ipsam",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8761),
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8765)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 14,
                            Body = "Dolor nihil maxime necessitatibus veniam aliquam dolor. Veritatis fugiat et sed qui et. Praesentium dolores modi dolorem. Omnis ab nulla nobis. Molestiae eius quasi molestiae consequuntur provident ut neque provident molestias.",
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8878),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 847, DateTimeKind.Local).AddTicks(8881)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDislike")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9585),
                            IsDislike = true,
                            IsLike = true,
                            PostId = 19,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9654),
                            UserId = 5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9745),
                            IsDislike = true,
                            IsLike = true,
                            PostId = 4,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9751),
                            UserId = 16
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9779),
                            IsDislike = true,
                            IsLike = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9783),
                            UserId = 6
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9808),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 4,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9812),
                            UserId = 18
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9836),
                            IsDislike = true,
                            IsLike = false,
                            PostId = 14,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9850),
                            UserId = 7
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9877),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9881),
                            UserId = 19
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9901),
                            IsDislike = true,
                            IsLike = true,
                            PostId = 9,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9904),
                            UserId = 9
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9918),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 18,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9921),
                            UserId = 13
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9933),
                            IsDislike = true,
                            IsLike = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9936),
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9950),
                            IsDislike = true,
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9953),
                            UserId = 4
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9965),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 10,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9967),
                            UserId = 13
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9979),
                            IsDislike = true,
                            IsLike = false,
                            PostId = 14,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9981),
                            UserId = 16
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9994),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 3,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 850, DateTimeKind.Local).AddTicks(9997),
                            UserId = 10
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 851, DateTimeKind.Local).AddTicks(10),
                            IsDislike = true,
                            IsLike = true,
                            PostId = 16,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 851, DateTimeKind.Local).AddTicks(12),
                            UserId = 12
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 851, DateTimeKind.Local).AddTicks(25),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 851, DateTimeKind.Local).AddTicks(27),
                            UserId = 17
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 851, DateTimeKind.Local).AddTicks(39),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 851, DateTimeKind.Local).AddTicks(42),
                            UserId = 8
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 851, DateTimeKind.Local).AddTicks(54),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 2,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 851, DateTimeKind.Local).AddTicks(57),
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 851, DateTimeKind.Local).AddTicks(68),
                            IsDislike = true,
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 851, DateTimeKind.Local).AddTicks(71),
                            UserId = 9
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 851, DateTimeKind.Local).AddTicks(82),
                            IsDislike = true,
                            IsLike = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 851, DateTimeKind.Local).AddTicks(84),
                            UserId = 16
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 851, DateTimeKind.Local).AddTicks(96),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 851, DateTimeKind.Local).AddTicks(99),
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 805, DateTimeKind.Local).AddTicks(936),
                            Email = "Shanna72@yahoo.com",
                            Password = "aOxwsXYVi4g2H7+ATjIcJKASROLNzOkE8NCaTyFyWLQ=",
                            Salt = "zoyRnFFrpDe96A1NPKEe8QfqiPsEi316ApYOm09gHYs=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 805, DateTimeKind.Local).AddTicks(1025),
                            UserName = "Irma68"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 806, DateTimeKind.Local).AddTicks(9195),
                            Email = "Gregory_Hagenes0@hotmail.com",
                            Password = "A0mmzRPYRb/XES4am874yy6YBbMAL1ytQWL3FfgjB5Q=",
                            Salt = "gBJPUMUIFmY5RuEHUgoa1wBlUNeWMbjeUZXLH4KAaGI=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 806, DateTimeKind.Local).AddTicks(9222),
                            UserName = "Rhiannon_Reinger"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 808, DateTimeKind.Local).AddTicks(7273),
                            Email = "Madaline.Wilderman14@gmail.com",
                            Password = "tjmNliALf4rG03JNv9i/SdZAX1PVmrC9ZskNIpXOJXo=",
                            Salt = "ZAQgCm9TYFXiiExDdBOoeo05mG84Nf+PTtZDwEi3MZg=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 808, DateTimeKind.Local).AddTicks(7301),
                            UserName = "Sigurd.Weimann"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 810, DateTimeKind.Local).AddTicks(6067),
                            Email = "Skye61@yahoo.com",
                            Password = "CH3IkzaSTaqIyCDq78rjGHikv9yKESw1T6sGpQ23tew=",
                            Salt = "cv30VVgoRzpvIr9Z+UuxuUrvWMfl2PZJpSaXz3pijQ4=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 810, DateTimeKind.Local).AddTicks(6113),
                            UserName = "Lenny_Jast7"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 812, DateTimeKind.Local).AddTicks(4460),
                            Email = "Tillman50@yahoo.com",
                            Password = "QRBknj/omzwz6P7uDqODzfcT72G42m8/2vveOh3WOOs=",
                            Salt = "jLEr+uWFyMqJt5s7xKsso52uVktZNXF+jD4pIlcSftU=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 812, DateTimeKind.Local).AddTicks(4487),
                            UserName = "Alexie94"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 814, DateTimeKind.Local).AddTicks(6061),
                            Email = "Gertrude_Murray@yahoo.com",
                            Password = "nJbp4YIJJT+LNfQw5mFWr7I66ftZUvNva7U20OAT4jc=",
                            Salt = "lR+MWmUVqj6nY2tZ2Hcvd/mE6MytuuYgabacsDowxfo=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 814, DateTimeKind.Local).AddTicks(6150),
                            UserName = "Uriah_Casper90"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 817, DateTimeKind.Local).AddTicks(1244),
                            Email = "Tyler.Considine93@hotmail.com",
                            Password = "hV6OYjDcrFNSXJ5G8xwzvS8g1KrMl0+8ss+6yrgAoGQ=",
                            Salt = "CMH/ybZgfPWtTmZGfsa3zKt2c89AfwHOCIxpfWdvXxU=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 817, DateTimeKind.Local).AddTicks(1289),
                            UserName = "Alessia.Herzog71"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 819, DateTimeKind.Local).AddTicks(2429),
                            Email = "Tyrel_Dietrich79@hotmail.com",
                            Password = "zG9TQDnOF5NgL7aSzQmwZkmVx3nHpz6AcT5+YX8X2Yo=",
                            Salt = "Fhv7sT45RIx9IGY4WL6HDprqAiZXP3IbD3yqkT8npGA=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 819, DateTimeKind.Local).AddTicks(2477),
                            UserName = "Kurtis.Kreiger79"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 821, DateTimeKind.Local).AddTicks(2680),
                            Email = "Clay.Kertzmann67@yahoo.com",
                            Password = "QF7+yx+8SFQH1+n2K2cP+dvcAcOEMJrrdIVkQaG9tnQ=",
                            Salt = "rmWBibo66mP4Mw0/gVYMLUcyE+Lov8IkR7hLX2Ln0Ww=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 821, DateTimeKind.Local).AddTicks(2729),
                            UserName = "Mac73"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 823, DateTimeKind.Local).AddTicks(825),
                            Email = "Neha0@yahoo.com",
                            Password = "Dv4FwzyVSRhlhMbqq1BfAgOJRZQ7hUyAD5YNyRE8FGo=",
                            Salt = "+br7QZJ0bJahgI62tS6ZXISVYwojKmG+c2hxdwfo4CU=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 823, DateTimeKind.Local).AddTicks(840),
                            UserName = "Rosie_Watsica"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 824, DateTimeKind.Local).AddTicks(8954),
                            Email = "Jaiden.Runolfsson@hotmail.com",
                            Password = "jhTp7MR72pGQWVfYGV9vRTgP/Ay0oHZRxHiXbjYeb5Q=",
                            Salt = "MZTfVECaj0Ht+ww7cjCxD5Sw42Hs0xb1TTqbXesRrlI=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 824, DateTimeKind.Local).AddTicks(8984),
                            UserName = "Jody0"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 826, DateTimeKind.Local).AddTicks(7184),
                            Email = "Laura_Fritsch23@hotmail.com",
                            Password = "3pVXdknswho7XvuPoJSegomz8tDRp0s/U3/ZNt5C6Ck=",
                            Salt = "TMtDIYjo6JxFkNLc3AZaXJyMoEMTCYAOeVQyNy0HLnI=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 826, DateTimeKind.Local).AddTicks(7208),
                            UserName = "Athena_Lesch69"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 828, DateTimeKind.Local).AddTicks(5579),
                            Email = "Martin.Grant89@gmail.com",
                            Password = "z1RB60x3oPfDA4ER2uhk7wjUPAQO5IsGSkCHBCzal1o=",
                            Salt = "NgvCp5tvwAY8NJsW9aur/uiX9+rSzl2HAGxmbyz5Hwc=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 828, DateTimeKind.Local).AddTicks(5618),
                            UserName = "Alphonso.Padberg"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 830, DateTimeKind.Local).AddTicks(6614),
                            Email = "Maurice55@hotmail.com",
                            Password = "WKRl7+KnmOOKy7t98wlMUu+Q8joilQD+AiveD4+nJhs=",
                            Salt = "13Z32L1Ru+FXkdQBV7jGlXwKdLgMdplmKtbZtSOcUmQ=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 830, DateTimeKind.Local).AddTicks(6656),
                            UserName = "Bettye.Breitenberg"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 832, DateTimeKind.Local).AddTicks(4999),
                            Email = "Jayce71@hotmail.com",
                            Password = "fYcJFQDFDd89pMs6wzCLY51RUtb0aW50Y6O3IJo4FaY=",
                            Salt = "PIguAX6ay7zmovIvYcpxkwGnedU18voTU4bDxxTDPxQ=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 832, DateTimeKind.Local).AddTicks(5032),
                            UserName = "Estella.Nader"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 834, DateTimeKind.Local).AddTicks(3274),
                            Email = "Lilla.Weimann@gmail.com",
                            Password = "Q/jDFbA8l1mGF9nhfjFXmyMmlaZ+6BZQLG7++fZSSU8=",
                            Salt = "xlryRpRyVPoFUaLzJO1alIYPO0GMZ9RNJWAu4BhsaE0=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 834, DateTimeKind.Local).AddTicks(3296),
                            UserName = "Uriah55"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 836, DateTimeKind.Local).AddTicks(3965),
                            Email = "Loy.Vandervort@yahoo.com",
                            Password = "fPWitOd6EOrWTpOLEdRNblX15nzCxqLYrFMRi1Xp7tU=",
                            Salt = "N+8ej/k8qAodwSxUyTbnpFOFVorBz0cOhV5LvqW31ro=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 836, DateTimeKind.Local).AddTicks(4018),
                            UserName = "Antonietta72"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 839, DateTimeKind.Local).AddTicks(178),
                            Email = "Germaine.Turner@hotmail.com",
                            Password = "3SfnytDE2zxkcDuvaJE799ly45RNv/6ItQbXxTVkVqI=",
                            Salt = "YEPyXf7c/QLPk+O4CvYCGPBGORNtv0a1zGDud5H3YnA=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 839, DateTimeKind.Local).AddTicks(214),
                            UserName = "Bria_Hauck"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 840, DateTimeKind.Local).AddTicks(9158),
                            Email = "Barton_Hand18@gmail.com",
                            Password = "KCA0i2RIxzGQRX+hTwTnFWXbS0nc0vdzLOfNaaD5xNM=",
                            Salt = "kCct1t4BE3+jKo2lQEKN6OE+9B+y9jZ2Pvae8rs2DL4=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 840, DateTimeKind.Local).AddTicks(9197),
                            UserName = "Casimer18"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 842, DateTimeKind.Local).AddTicks(8028),
                            Email = "Kris_Wunsch@hotmail.com",
                            Password = "BB0++6ti0CMLsmAYgqGBzS60eBSsXm0RrW15c+OjLEo=",
                            Salt = "sKe79CZ9eUt3gJ/67yGciSp2ONmAoF6580hCs+F0Zq4=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 842, DateTimeKind.Local).AddTicks(8073),
                            UserName = "Rafaela_Champlin56"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 845, DateTimeKind.Local).AddTicks(2394),
                            Email = "test@gmail.com",
                            Password = "4X6JK6XeTbmnVFfgeKrVPMKGkb3Ql8rufeWOi6C6VfI=",
                            Salt = "2lZWMqSZS6KILPqQpX9g6xWTfVPXDB2JG1f3cLHuyNU=",
                            UpdatedAt = new DateTime(2023, 1, 27, 0, 6, 15, 845, DateTimeKind.Local).AddTicks(2394),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Preview");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
