// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

#nullable disable

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20230128150533_CorrectData")]
    partial class CorrectData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 10,
                            Body = "Voluptas eaque qui eum.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 786, DateTimeKind.Local).AddTicks(8125),
                            PostId = 2,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 786, DateTimeKind.Local).AddTicks(8288)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 6,
                            Body = "Amet voluptas veritatis nihil ducimus eveniet ut laudantium nam in.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 786, DateTimeKind.Local).AddTicks(8930),
                            PostId = 20,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 786, DateTimeKind.Local).AddTicks(8952)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 12,
                            Body = "Maxime consequuntur ex rerum aliquam unde.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 786, DateTimeKind.Local).AddTicks(9134),
                            PostId = 11,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 786, DateTimeKind.Local).AddTicks(9144)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Body = "Fugiat odit est asperiores officiis dicta et et corrupti.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 786, DateTimeKind.Local).AddTicks(9317),
                            PostId = 3,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 786, DateTimeKind.Local).AddTicks(9329)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            Body = "Porro quia odit ducimus eaque ut est dignissimos.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 786, DateTimeKind.Local).AddTicks(9482),
                            PostId = 12,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 786, DateTimeKind.Local).AddTicks(9496)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            Body = "Minus provident laboriosam qui animi non enim excepturi perspiciatis accusantium.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 786, DateTimeKind.Local).AddTicks(9715),
                            PostId = 7,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 786, DateTimeKind.Local).AddTicks(9730)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            Body = "Non labore ut sit ea harum sed sed.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(121),
                            PostId = 10,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(131)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 17,
                            Body = "Sed eum iure iste dolor cum temporibus aut cumque.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(340),
                            PostId = 10,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(567)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 17,
                            Body = "Odio eveniet unde accusamus et deleniti ullam velit consequatur debitis.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(895),
                            PostId = 20,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(906)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 4,
                            Body = "Sint deserunt deserunt ratione at.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(1107),
                            PostId = 14,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(1121)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 11,
                            Body = "Animi rem quia vero accusamus reiciendis.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(1360),
                            PostId = 10,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(1389)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 9,
                            Body = "Illum officiis et quia quisquam fugit aliquid totam ullam.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(1619),
                            PostId = 2,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(1635)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 6,
                            Body = "Dolores assumenda consectetur beatae vel aut.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(1829),
                            PostId = 3,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(1840)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 1,
                            Body = "Eos aut ipsam sit commodi.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(1990),
                            PostId = 15,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(2000)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 13,
                            Body = "Sit dolor laudantium harum est adipisci in velit.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(2197),
                            PostId = 19,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(2209)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 13,
                            Body = "Temporibus quo a fugit incidunt.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(2374),
                            PostId = 1,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(2385)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 2,
                            Body = "Sapiente et voluptatem.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(2518),
                            PostId = 4,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(2532)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 20,
                            Body = "Dolor nihil nesciunt dolore aliquid illo.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(2700),
                            PostId = 12,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(2715)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 13,
                            Body = "Quidem nihil porro quia voluptatem atque enim dolor dolor sapiente.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(2920),
                            PostId = 1,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(2935)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 2,
                            Body = "Expedita rem voluptates ex earum quis laudantium aspernatur illum dolor.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(3170),
                            PostId = 7,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 787, DateTimeKind.Local).AddTicks(3186)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDislike")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 6,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5200),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5338),
                            UserId = 8
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 17,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5648),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5658),
                            UserId = 7
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 10,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5790),
                            IsDislike = true,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5797),
                            UserId = 17
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 18,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5836),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5843),
                            UserId = 19
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 8,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5877),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5883),
                            UserId = 12
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 11,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5914),
                            IsDislike = true,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5919),
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 5,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5950),
                            IsDislike = true,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5955),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 16,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5985),
                            IsDislike = true,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(5990),
                            UserId = 13
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 15,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6021),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6026),
                            UserId = 16
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 9,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6094),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6099),
                            UserId = 11
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 20,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6134),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6139),
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 12,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6168),
                            IsDislike = true,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6174),
                            UserId = 20
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 20,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6203),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6208),
                            UserId = 10
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 2,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6237),
                            IsDislike = true,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6242),
                            UserId = 9
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 2,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6270),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6275),
                            UserId = 21
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 15,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6303),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6308),
                            UserId = 17
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 10,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6334),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6339),
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 17,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6364),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6370),
                            UserId = 21
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 7,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6398),
                            IsDislike = true,
                            IsLike = false,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6404),
                            UserId = 5
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 18,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6434),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 795, DateTimeKind.Local).AddTicks(6440),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6380),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/979.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6486)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6601),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/654.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6611)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6637),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/927.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6643)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6663),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/821.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6669)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6691),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1225.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6696)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6723),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1089.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6733)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6766),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/184.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6775)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6814),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1042.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6821)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6856),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/683.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6864)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6898),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/339.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6906)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6940),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/7.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6948)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6984),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/227.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(6992)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7030),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1119.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7038)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7072),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/575.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7081)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7118),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/334.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7126)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7165),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1123.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7173)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7229),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/984.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7239)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7281),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/534.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7290)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7326),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1061.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7336)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7374),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/187.jpg",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 711, DateTimeKind.Local).AddTicks(7383)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3172),
                            URL = "https://picsum.photos/640/480/?image=34",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3260)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3372),
                            URL = "https://picsum.photos/640/480/?image=1045",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3380)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3410),
                            URL = "https://picsum.photos/640/480/?image=642",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3417)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3443),
                            URL = "https://picsum.photos/640/480/?image=432",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3449)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3474),
                            URL = "https://picsum.photos/640/480/?image=203",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3480)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3503),
                            URL = "https://picsum.photos/640/480/?image=242",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3508)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3533),
                            URL = "https://picsum.photos/640/480/?image=770",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3540)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3562),
                            URL = "https://picsum.photos/640/480/?image=703",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3568)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3595),
                            URL = "https://picsum.photos/640/480/?image=838",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3600)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3633),
                            URL = "https://picsum.photos/640/480/?image=701",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3639)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3665),
                            URL = "https://picsum.photos/640/480/?image=230",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3671)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3696),
                            URL = "https://picsum.photos/640/480/?image=871",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3702)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3726),
                            URL = "https://picsum.photos/640/480/?image=136",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3732)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3755),
                            URL = "https://picsum.photos/640/480/?image=64",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3761)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3785),
                            URL = "https://picsum.photos/640/480/?image=1076",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3791)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3813),
                            URL = "https://picsum.photos/640/480/?image=700",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3819)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3841),
                            URL = "https://picsum.photos/640/480/?image=955",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3846)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3871),
                            URL = "https://picsum.photos/640/480/?image=231",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3877)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3900),
                            URL = "https://picsum.photos/640/480/?image=611",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3906)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3929),
                            URL = "https://picsum.photos/640/480/?image=584",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 715, DateTimeKind.Local).AddTicks(3935)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PreviewId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 19,
                            Body = "Id vel iusto aut aspernatur inventore. Ab blanditiis est consequatur. Porro sit tempora quae et commodi. Velit rerum fugit incidunt officia expedita nesciunt qui cum nihil. Aut maxime sit quo placeat exercitationem facere.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(2527),
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(2635)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 14,
                            Body = "Tenetur ipsa omnis animi non doloribus animi.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(3150),
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(3181)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 10,
                            Body = "Aperiam hic voluptatibus dolorem.\nEa earum et.\nQuo expedita reiciendis quis similique consequuntur ea.\nRepellat debitis dolorum non eos iste perspiciatis.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(3523),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(3533)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            Body = "dolorem",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(3614),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(3638)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 17,
                            Body = "Quia sint dolorum blanditiis ut.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(3822),
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(3839)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 21,
                            Body = "Nam iste reprehenderit.\nIusto repudiandae id nam veritatis facere temporibus.\nConsequatur iste dolorem.\nSequi iste cupiditate deleniti odio.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(4323),
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(4333)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 5,
                            Body = "Omnis quia neque neque facere qui qui illum.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(4474),
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(4484)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            Body = "Labore consequatur harum pariatur sed quam.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(4656),
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(4672)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 8,
                            Body = "laudantium",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(4748),
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(4759)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 13,
                            Body = "Quod et officiis aliquam ea non dolorum et. Velit sit ut error pariatur. Et deleniti ipsam minima velit inventore earum. Nihil magni rem.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(5124),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(5136)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 16,
                            Body = "maiores",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(5200),
                            PreviewId = 34,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(5209)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 14,
                            Body = "assumenda",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(5263),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(5270)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 15,
                            Body = "Eveniet ipsa reprehenderit qui deleniti porro.\nOccaecati debitis ea occaecati neque.\nEa deleniti inventore ipsa qui et.\nIste atque vel sed distinctio in corrupti tempore accusantium est.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(5818),
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(5836)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 13,
                            Body = "Aliquid neque laboriosam est repellat vero quisquam quam sint.\nFugiat cum rerum sunt ullam beatae labore dolores perferendis.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(6231),
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(6255)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 12,
                            Body = "Sint sunt voluptates vel ea alias. Quam asperiores ut aut deserunt nisi id quia quidem ipsum. Quo dolorem enim vitae mollitia recusandae voluptas. Rem ducimus doloribus.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(6695),
                            PreviewId = 30,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(6711)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 5,
                            Body = "tempore",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(6774),
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(6781)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 11,
                            Body = "Saepe a facere eius. Et enim suscipit id. Blanditiis et ducimus quaerat.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(6995),
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(7006)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 20,
                            Body = "Consequatur facilis provident autem vitae libero sint.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(7122),
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(7129)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 3,
                            Body = "Exercitationem quo ullam aspernatur culpa labore aut repudiandae dolorem ullam. Earum enim corporis doloribus qui dolorem voluptates. Labore voluptas exercitationem sit sint possimus. Tenetur est placeat sint recusandae ratione perferendis quia. Quas architecto quas praesentium perspiciatis animi veniam perferendis accusantium.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(7811),
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(7836)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 8,
                            Body = "Vero eum in reprehenderit qui.",
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(8015),
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 782, DateTimeKind.Local).AddTicks(8029)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDislike")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(6897),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7008),
                            UserId = 5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7192),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 17,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7202),
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7242),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 19,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7249),
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7284),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 5,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7290),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7325),
                            IsDislike = true,
                            IsLike = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7330),
                            UserId = 12
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7361),
                            IsDislike = true,
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7367),
                            UserId = 12
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7400),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 12,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7405),
                            UserId = 9
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7440),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 16,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7445),
                            UserId = 10
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7478),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7483),
                            UserId = 7
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7518),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 14,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7523),
                            UserId = 19
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7554),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 13,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7559),
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7590),
                            IsDislike = true,
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7595),
                            UserId = 15
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7625),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7630),
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7667),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7673),
                            UserId = 13
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7792),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 10,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7802),
                            UserId = 14
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7857),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7866),
                            UserId = 17
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7920),
                            IsDislike = true,
                            IsLike = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7946),
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7979),
                            IsDislike = true,
                            IsLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(7984),
                            UserId = 6
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(8029),
                            IsDislike = true,
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(8034),
                            UserId = 13
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(8062),
                            IsDislike = true,
                            IsLike = false,
                            PostId = 14,
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 791, DateTimeKind.Local).AddTicks(8067),
                            UserId = 15
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 723, DateTimeKind.Local).AddTicks(1986),
                            Email = "Domenico21@gmail.com",
                            Password = "4XcB2Kuvobey/uDmeVllcag4B2iHdWXw1yiNXlGtwME=",
                            Salt = "L89fP9BvCpXkQN3aTIR2EjsavsJHacA8rGcZ7XFPSvA=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 723, DateTimeKind.Local).AddTicks(2099),
                            UserName = "Marcelle56"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 727, DateTimeKind.Local).AddTicks(6997),
                            Email = "Cicero_Schimmel50@hotmail.com",
                            Password = "50YHd4O1eoZIWlLfMA2L/UA0RQwXtmLCjqk1Q0Zt6oI=",
                            Salt = "ZDFRJtMBZUnthp9CHPkfYtS6S8Qh0ngqpzYM624fXLM=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 727, DateTimeKind.Local).AddTicks(7022),
                            UserName = "Bernie39"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 731, DateTimeKind.Local).AddTicks(7382),
                            Email = "Keeley_Lesch@yahoo.com",
                            Password = "TPdoKbfGqnSWgyoiqu36yg+igxbyiWDsZ9WCHEFIXrY=",
                            Salt = "YmGDEjqo2oBekT93K91f8eaKkGngPU0k3UAcsHiMNRA=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 731, DateTimeKind.Local).AddTicks(7438),
                            UserName = "Hertha.Feil1"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 735, DateTimeKind.Local).AddTicks(2774),
                            Email = "Elmer_Maggio@hotmail.com",
                            Password = "t+q8b2M8atJp0Xs6byTT35MY5uY9YnfgAQTY7mS2JyQ=",
                            Salt = "WsSs39489gkeANWcavoh4HiOQe6JqaRwXmaLSEytq7Q=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 735, DateTimeKind.Local).AddTicks(2795),
                            UserName = "Elbert28"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 738, DateTimeKind.Local).AddTicks(8902),
                            Email = "Madelyn_Crist65@gmail.com",
                            Password = "6//E2p4OskB5ZuSHgO8GCzUKw7tlM+UXlqbJKOTD5pk=",
                            Salt = "L963mrPrVLQBYSRnGP3LcFRBigR6XpzwV58bwHv3VEI=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 738, DateTimeKind.Local).AddTicks(8916),
                            UserName = "Arnulfo.Johnston"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 742, DateTimeKind.Local).AddTicks(175),
                            Email = "Brionna91@yahoo.com",
                            Password = "4VJ3rXcnTb9V8+YhW0k0pxKN2Wx+GGWB5ocyjlIowHg=",
                            Salt = "jOkwCYtmTtSBcd/FyopdAKTKTxdcZJM28HZ1xTjItKg=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 742, DateTimeKind.Local).AddTicks(200),
                            UserName = "Timothy.Grady6"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 745, DateTimeKind.Local).AddTicks(1508),
                            Email = "Camila.Connelly@gmail.com",
                            Password = "/4GokuaTqJ7Ag+pPy4KoTu/2MmA160jfrMG963eV/iw=",
                            Salt = "yB0+7EFcCgLEWHiLLY0jZfSFNqqY2/T9bv7lBTMJsmw=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 745, DateTimeKind.Local).AddTicks(1532),
                            UserName = "Emmett_Dickinson33"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 748, DateTimeKind.Local).AddTicks(2385),
                            Email = "Carissa74@hotmail.com",
                            Password = "/Irkf1Tamy+KrUy12GGDzoSDsutGknQWoXHFRVsDyc0=",
                            Salt = "54p8g4BGlMadZcWT3kyneHA0arIoa8rJD9r4QLtXuDU=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 748, DateTimeKind.Local).AddTicks(2682),
                            UserName = "Hillary33"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 751, DateTimeKind.Local).AddTicks(2229),
                            Email = "Mallie8@yahoo.com",
                            Password = "78ox5dSSE2IMkx+JLH/YI/kBSYTMf36O1HMKZleApkI=",
                            Salt = "4+ihowSKPPVVLipWJtwMQVANCb3pb5RAOyd9Wyg1NvY=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 751, DateTimeKind.Local).AddTicks(2238),
                            UserName = "Easter.Turcotte"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 753, DateTimeKind.Local).AddTicks(7282),
                            Email = "Ressie_Ernser65@yahoo.com",
                            Password = "LLfXTyqPq2vdViynLAxBohr1Vc6a2Z6HImVoJcaH+6M=",
                            Salt = "nxtjLf1Oi3/1U2dC20NnkbNW1mNSRHwnf0xNz/YwFok=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 753, DateTimeKind.Local).AddTicks(7293),
                            UserName = "Damien.Emmerich15"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 756, DateTimeKind.Local).AddTicks(3642),
                            Email = "Ardella.Feest@hotmail.com",
                            Password = "Y1w/tzW/jQyOz8vz9K2NVUFVs87aB//2xAmcDnQLv5Q=",
                            Salt = "BLwCeE09agiNJTq9XAFlU0uSuWRQLoqVSvcguYkmKAU=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 756, DateTimeKind.Local).AddTicks(3674),
                            UserName = "Gwen.Gaylord14"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 758, DateTimeKind.Local).AddTicks(7604),
                            Email = "Garfield71@gmail.com",
                            Password = "Sg883xLbkkU7gKHmwRRxkkeQa/rA0QdMqxdjwQF/07g=",
                            Salt = "odYHrGwQrlDcKWsrOUVq5TBz73126RoEIGcDHkq2Lug=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 758, DateTimeKind.Local).AddTicks(7613),
                            UserName = "Mercedes_Hilll89"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 760, DateTimeKind.Local).AddTicks(9122),
                            Email = "Johnnie_Dickinson@hotmail.com",
                            Password = "EzV16xFKcrNwEA1OpDycWQgzIKhAHSUzbLxowebsLTI=",
                            Salt = "EEY6N9VTkUgG8JuJadfDc9go192V8UUFdb0WjLDC4CA=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 760, DateTimeKind.Local).AddTicks(9128),
                            UserName = "Ephraim81"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 763, DateTimeKind.Local).AddTicks(1356),
                            Email = "Dortha_Hilll43@gmail.com",
                            Password = "N7l/mMEreof4WuGnxM8wKakaF0Q3Wp8o3kgUp3Elfvc=",
                            Salt = "Mb7XHsb5160D4bPPj7fkD0e2c+ewjTWnJGarB5HFvFc=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 763, DateTimeKind.Local).AddTicks(1390),
                            UserName = "Royal21"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 765, DateTimeKind.Local).AddTicks(1770),
                            Email = "Timothy10@hotmail.com",
                            Password = "7V61bOt5CAXplw3pLPOE+AbweyLJEo3zYXzAPjL+BzI=",
                            Salt = "Ro8yFWUGAx+47Ipz5Zpz5JSJzCrTYIXFoFQJWtBPtB0=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 765, DateTimeKind.Local).AddTicks(1775),
                            UserName = "Ulises.Green"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 766, DateTimeKind.Local).AddTicks(9175),
                            Email = "Bailey_Kshlerin@hotmail.com",
                            Password = "MPd0ZAn99MAdfI6f9QnWV5Da8gATuBgLdkbTyV4XLWc=",
                            Salt = "DpTqg6dqZFel0qPE2DyLnLvouT1fKKqJd/k4VMrRtTg=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 766, DateTimeKind.Local).AddTicks(9179),
                            UserName = "Icie27"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 768, DateTimeKind.Local).AddTicks(6376),
                            Email = "Sofia.Schuppe79@yahoo.com",
                            Password = "AoAA5Z3LbjhAA4oUze/HapRswlVGWqgiRa99FT5kGFI=",
                            Salt = "DZ7xTzL8NTY7lu/2Jt0u0ierNF2b3GVE/x00F3gW6g8=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 768, DateTimeKind.Local).AddTicks(6380),
                            UserName = "Trenton_Larkin"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 770, DateTimeKind.Local).AddTicks(3774),
                            Email = "Susana29@hotmail.com",
                            Password = "IR8pUPJehjYV5NFN1RJBmxAL8CTcsv4KljTqHZfkDL4=",
                            Salt = "se1ATfPM2a3MVOXemh85W/PrnqvTI2X7sO48wjdLIPI=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 770, DateTimeKind.Local).AddTicks(3777),
                            UserName = "Mallory_Toy"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 772, DateTimeKind.Local).AddTicks(6378),
                            Email = "Shane.Ondricka@hotmail.com",
                            Password = "iQ10ygxANzm7j1RFAKb0p+/Gjx/ENo9nqTbN38azfaw=",
                            Salt = "txho9ogVc4pNBwbJiekajeham0z8TQATar+EqoPWceE=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 772, DateTimeKind.Local).AddTicks(6425),
                            UserName = "Estel1"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 776, DateTimeKind.Local).AddTicks(9078),
                            Email = "Freeman_Hintz21@yahoo.com",
                            Password = "TqogGfhB0pxpoT7KCkAscgDezII0kSLTJSly30ECEcQ=",
                            Salt = "P168B3tWqNMYW65PLBBaW0Ez8aNodQDCJIJ6r9pNWtY=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 776, DateTimeKind.Local).AddTicks(9141),
                            UserName = "Hettie52"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 779, DateTimeKind.Local).AddTicks(3177),
                            Email = "test@gmail.com",
                            Password = "q9KIjKVihdQ/BM+LG9qVGc8CV/hDMw2IyjU80dg0W/4=",
                            Salt = "fzo/HueJXGVLtQuhGaTjOHT+sYuZfRG09jqlWRfCFU8=",
                            UpdatedAt = new DateTime(2023, 1, 28, 17, 5, 32, 779, DateTimeKind.Local).AddTicks(3177),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Preview");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
